name: Build and Deploy

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        env:
          DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}

      # - name: Publish
      #   run: dotnet publish src/Endpoint/Endpoint.csproj -c Release -o publish

      # # 以下步骤取决于你的部署目标（Azure, AWS, GCP等）
      # # 这是一个Azure Web App的示例
      # - name: Deploy to Azure Web App
      #   if: github.ref == 'refs/heads/main' # 只在main分支上部署
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: "your-app-name"
      #     slot-name: "production"
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: "./publish"
      #   env:
      #     DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
